### ISSUE TITLE
Swapped cpu and gpu

### ISSUE THREAD

**Issue by lukeyeager** [mapler/dockerfiles#1]
https://github.com/mapler/dockerfiles/blob/a5d4fa18baa3ced264b5810835f8d03e31eb5628/caffe-py3-cpu/Dockerfile#L1
https://github.com/mapler/dockerfiles/blob/a5d4fa18baa3ced264b5810835f8d03e31eb5628/caffe-py3-gpu/Dockerfile#L1

**Comment by edregansolution** [comment]
Hi Luke
What is your skype?
I would like to get a help from you on my current project.
It is about NVIDIA digits object detection, and I have image data sets for training.
I'm failed to create models with various error codes, so I would like you help me.
Looking forward to hearing from you.
Thank you
Edward

**Comment by mapler** [comment]
@lukeyeager sorry for replying so late
It's a big mistake 😱.

**Comment by fberanizo** [comment]
Hello!
I guess the build step for the cpu image was also copied from the wrong image:

https://github.com/mapler/dockerfiles/blob/5d8b88f847aa3c65feedad5f8a98cb4ae90bfc96/caffe-py3-cpu/Dockerfile#L34-L39

https://github.com/BVLC/caffe/blob/04ab089db018a292ae48d51732dd6c66766b36b6/docker/cpu/Dockerfile#L34-L39
