### ISSUE TITLE
Upgrading pip (from 8.1.1) to most recent build breaks your pip installs

### ISSUE THREAD

**Issue by bravecorvus** [mapler/dockerfiles#2]
Not really sure why, but it seems the `pip3 install --upgrade pip` command right before you install all the dependencies in `requirements.txt`, `pydot`, and `python-dateutils>2` for your code in  `caffe-py3-gpu`.

I will be making a pull request with the suggested fixes in a sec (only for `caffe-py3-gpu`). Please note your other Dockerfiles might have the same issues.

## Problem
![img1](https://66.media.tumblr.com/e97bb8541c333bb7595fdc06c40ec1b9/tumblr_plsn4rN12g1xbkxdso1_1280.png)

## Fixed
![img2](https://66.media.tumblr.com/8688f45e5689c75500739934d0af444b/tumblr_plsn4rN12g1xbkxdso2_1280.png)

**Comment by mapler** [comment]
Sorry for taking so long to reply.
I'm not using caffe now. and missed checking github PR.

Seems some problem in pip. (https://github.com/pypa/pip/issues/5221)
